### ISSUE TITLE
Dagda does not list running containers in MacOS

### ISSUE THREAD

**Issue by ab9-er** [eliasgranderubio/dagda#11]
I am using Docker-Machine on MacOS. Dagda is unable to check the containers and images that are currently running. Instead, it raises a 404. Is there a way to force Dagda to hit a custom `DOCKER_HOST` ?

**Comment by eliasgranderubio** [comment]
Hi @ab9-er ,

At the moment, Dagda hits against docker unix socket and it does not support the remote access through the tcp socket. You can check this in the next line:

* [L32](https://github.com/eliasgranderubio/dagda/blob/master/dagda/driver/docker_driver.py#L32)

By default, a unix domain socket is created at `/var/run/docker.sock`, requiring either root permission, or docker group membership. If you get a 404 HTTP error, you could have a new Dagda issue in the server log. Could you check it?

**Comment by ab9-er** [comment]
@eliasgranderubio So basically what is happening is this when I do a `python dagda.py docker containers`

```
dagda/dagda/api/service/docker.py", line 51, in get_all_running_containers
    containers = InternalServer.get_docker_driver().get_docker_client().containers()
AttributeError: 'NoneType' object has no attribute 'containers'
```

**Comment by eliasgranderubio** [comment]
I've just upgrade the docker-py requirement to `docker==2.2.0` and I have tested to list the containers and images again and it looks like work fine.

Before you up-to-date with master branch for testing it, execute the next command for cleaning previous requirements:
```
   python3 -m pip uninstall docker-py docker
```

Does the error persits?

**Comment by ab9-er** [comment]
Yes. No improvement.

**Comment by eliasgranderubio** [comment]
If you remove the next lines (try-except) and restart the server:
* https://github.com/eliasgranderubio/dagda/blob/master/dagda/driver/docker_driver.py#L33
* https://github.com/eliasgranderubio/dagda/blob/master/dagda/driver/docker_driver.py#L35
* https://github.com/eliasgranderubio/dagda/blob/master/dagda/driver/docker_driver.py#L36
* https://github.com/eliasgranderubio/dagda/blob/master/dagda/driver/docker_driver.py#L37

Have you any different errors? Does the docker module for python works fine in MacOS?

I think you are the first person that run Dagda in MacOS, so Dagda could have several unknown issues in this distribution.

**Comment by ab9-er** [comment]
It breaks the server completely 🤕
```
dagda/lib/python3.6/site-packages/docker/api/client.py", line 168, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by eliasgranderubio** [comment]
I've been seeing issues related with 'unix://var/run/docker.sock: No such file or directory' and it looks like a very common issue in MacOS.

If you replace the `unix://var/run/docker.sock` with `tcp://{IpAddress}:{Port}` (DOCKER_HOST) or the `client = docker.APIClient(base_url='unix://var/run/docker.sock', version="auto", timeout=3600)` with `client = docker.from_env()`, is your problem fixed?

**Comment by eliasgranderubio** [comment]
Now, Dagda uses a docker client configured in the same way that Docker command-line client so your issue should be fixed. 

 @ab9-er, could you test it and give me feedback?

**Comment by ab9-er** [comment]
Steps:

```
docker pull mongo
docker run -d -p 27017:27017 mongo
pip install -U -r requirements.txt
python dagda/dagda.py start -m 172.16.185.129
python dagda/dagda.py docker containers
python dagda/dagda.py docker images
```

Error: (for listing both containers and images)
```
Traceback (most recent call last):
  File "dagda.py", line 130, in <module>
    main(DagdaCLIParser())
  File "/tmp/dagda/dagda/cli/dagda_cli_parser.py", line 36, in __init__
    super(DagdaCLIParser, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```

**Comment by ab9-er** [comment]
Infact this is the error for any CLI command.

**Comment by ab9-er** [comment]
This is no longer an issue, I am closing it. Thanks a lot @eliasgranderubio 👍🏻

**Comment by eliasgranderubio** [comment]
Anyway, you only can get the `TypeError: super() argument 1 must be type, not classobj` if you try to run dagda with python 2.7. Remember that this python version is not supported.

At the moment, Dagda only supports the next python versions:
* 3.3.X
* 3.4.X
* 3.5.X
* 3.6.X
