### ISSUE TITLE
JSON decoder ValueError in CLI with None value

### ISSUE THREAD

**Issue by eliasgranderubio** [eliasgranderubio/dagda#12]
I create this new issue for fixing the CLI problem described by @scumfrog in #10. The issue details is shown in this [comment](https://github.com/eliasgranderubio/dagda/issues/10#issuecomment-288987847).

The error that he gets is the next one: 
```
# python3 dagda.py vuln --init                        
Traceback (most recent call last):
  File "dagda.py", line 125, in <module>
    main(DagdaCLIParser())
  File "dagda.py", line 121, in main
    print(json.dumps(json.loads(r.content.decode('utf-8')), sort_keys=True, indent=4))
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by eliasgranderubio** [comment]
@scumfrog All REST API responses have body even though the responses are errors. So, if you do the same request with `curl` to the REST API: [vuln init](https://github.com/eliasgranderubio/dagda/wiki/REST-API#vulninit), what is the HTTP error shown?

**Comment by scumfrog** [comment]
Hello @eliasgranderubio 

After testing all weekend, i can assume that error is comming from some connectivity issue:

```
# curl http://localhost:5000/v1/vuln/init-status

{  
   "status":"Unexpected exception of type ConnectionError occured: (MaxRetryError(\"HTTPSConnectionPool(host='static.nvd.nist.gov', port=443): Max retries exceeded with url: /feeds/xml/cve/nvdcve-2.0-2002.xml.gz (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4550841470>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)",
   "timestamp":"2017-03-27 08:26:07.959964"
}

```
I think that i've some proxy issues in the enviroment. I close the issue. Thanks in advance @eliasgranderubio !! :+1:

**Comment by eliasgranderubio** [comment]
That looks like connectivity issue as you write. Anyway, I'm concern about the empty response which causes the previous error:   
```
  ...
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

I've tried to raise unexpected errors from many code sides but I can't reproduce the error. Could you try to reproduce the error in your environment and attach me the HTTP status code or message/error when you query to `vuln/init`?

**Comment by scumfrog** [comment]
@eliasgranderubio as i told you, yes, it was the proxy of my enviroment. I think, if you want to reproduce the error, you can force use a proxy server with a security policy that denies "*.nvd.nist.gov". I used the  `export http_proxy=proxy` option. For the tty where i execute the server, it works nice (dadga use the proxy to connect to the feeds), but if the env variable are setting on the CLI tty, the error occurs.

**Comment by eliasgranderubio** [comment]
Ok, I close this issue.

If you find another one, feel free to open it ;-)
