### ISSUE TITLE
exec sleep error

### ISSUE THREAD

**Issue by xinity** [eliasgranderubio/dagda#18]
hi here,

while trying to analyze for testing the docker image traefik:latest, i had these strange bugs comes up while using dagda:
```
dagda     | 
docker.errors.NotFound: 404 Client Error: Not Found for url: 
http+docker://localunixsocket/v1.28/containers/10851416f569e8489dcc9006baec6751c68e76eeeafb7a233319ff37d6916f32/start ("oci runtime error: container_linux.go:247: 
starting container process caused "exec: \"sleep\": executable file not found in $PATH"
```
anyone knows how to fix perhaps ?

thanks alot !

**Comment by eliasgranderubio** [comment]
Traefik uses `scratch` as its Linux base image as far as I see in its [Dockerfile](https://github.com/containous/traefik-library-image/blob/50d631ddf197da6228172cb86ab6098d875a6ea0/Dockerfile). 

At the moment this Linux base image is not supported by Dagda, so if you want contribute, the PR will be welcome.

Anyway, I have improved the error control system for avoiding that Dagda crashes when unexpected error occurs by not supported Linux base images.

**Comment by xinity** [comment]
thanks a lot !
seems better now

i'll see if i can contribute a PR :)

**Comment by eliasgranderubio** [comment]
I'm glad to know that issue seems fixed. I close this issue then.

If you find a new issue, feel free for reporting it ;-)
