### ISSUE TITLE
JSONDecodeError doesn't exist before Python 3.5

### ISSUE THREAD

**Issue by keepwatch** [eliasgranderubio/dagda#20]
When doing a first-time setup (e.g. with REST API endpoint `vuln/init`), I get the following error: 

    AttributeError: 'module' object has no attribute 'JSONDecodeError'

It looks like you are expecting `json.JSONDecodeError` [here](https://github.com/eliasgranderubio/dagda/blob/master/dagda/vulnDB/ext_source_util.py#L224) to fire when the bugtraq data cannot be properly decoded. However, this error class was first added in Python 3.5 (compare [3.4](https://github.com/python/cpython/blob/3.4/Lib/json/decoder.py) and [3.5](https://github.com/python/cpython/blob/3.5/Lib/json/decoder.py#L20)), and the system requirements only state Python3.3+ is required.

Although you could simply bump the version requirement in the readme, would you consider making this compatable with < 3.5 Python? For example, Ubuntu 14.05's builtin Python3 is only 3.4.3.

**Comment by eliasgranderubio** [comment]
I agree with you. I should not have used `json.JSONDecodeError` for avoiding compatibility issues. Could you check this issue again for checking if it is fixed?

Thanks in advance.

**Comment by keepwatch** [comment]
I'm not getting the AttributeError any longer - after dropping and reinitializing the database, everything was imported without error. Thank you!
