### ISSUE TITLE
unable to start the dagda 

### ISSUE THREAD

**Issue by sudheer464** [eliasgranderubio/dagda#39]
when i was running this command, python3 dagda.py start

getting below error, 
ubuntu@ip-172-31-11-35:~/docker-security/dagda/dagda$ python3 dagda.py start
<2018-09-28 19:50:12,142> <ERROR> <DagdaServer> <docker_driver> <__init__:39> <Error while fetching Docker server API version: Assuming Travis CI tests.>
<2018-09-28 19:50:12,174> <ERROR> <DagdaServer> <dagda> <main:46> <'NoneType' object has no attribute 'events'>
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/home/ubuntu/docker-security/dagda/dagda/cli/dagda_cli.py", line 43, in execute_dagda_cmd
    ds.run()
  File "/home/ubuntu/docker-security/dagda/dagda/api/dagda_server.py", line 92, in run
    docker_daemon_events_monitor.run()
  File "/home/ubuntu/docker-security/dagda/dagda/analysis/runtime/docker_events_monitor.py", line 45, in run
    for event in self.docker_driver.docker_events():
  File "/home/ubuntu/docker-security/dagda/dagda/driver/docker_driver.py", line 114, in docker_events
    return self.cli.events()
AttributeError: 'NoneType' object has no attribute 'events'
<2018-09-28 19:50:12,199> <ERROR> <DagdaServer> <dagda_server> <run:103> <Error while fetching Docker server API version.>
<2018-09-28 19:50:12,200> <WARNING> <DagdaServer> <dagda_server> <run:104> <Runtime behaviour monitor disabled.>

i followed your github page and performed the all necessary actions.

**Comment by eliasgranderubio** [comment]
Hi @sudheer464 ,

It's the first time I see an issue like this in the `docker_driver.py` script. Could you share with me which is your docker version that you have installed in your host?

Best regards.

**Comment by sudheer464** [comment]
sudo docker --version
Docker version 18.03.1-ce, build 9ee9f40

**Comment by eliasgranderubio** [comment]
I've just update all external dependencies of the Dagda project and I've test the updated project with the docker version `Docker version 18.06.1-ce, build e68fc7a`, which is the last one, and all works fine.

Please, test again and give me feedback about if this last commit fixes this issue.

**Comment by eliasgranderubio** [comment]
Hi @sudheer464 ,

Could you give me any feedback about this issue?

**Comment by eliasgranderubio** [comment]
I close this issue because I have not any feedback about it for a long time. 

Please, if the error persists, reopen it.
