### ISSUE TITLE
Dagda starting with custom mongoDB crashes

### ISSUE THREAD

**Issue by Docteur-RS** [eliasgranderubio/dagda#43]
### Short description

First I must say that this is an impressive piece of software ! Good job !

---

I tried to connect Dagda to my own mongoDB database but it crashes.

### Reproduction steps

That's what I did :
```
docker pull mongo
docker run -d -p 27017:27017 mongo
```
Next I populated the database myself (not using vuln init) though the error appears with the db populated or not.

Finally I started Dagda using the 3grander/dagda image :
`docker run 40c9973099f7 start -m 192.168.99.100 -mp 27017`

### Expected results

I expected that Dagda server would be up and running and that I could query it using either CLI or the HTTP API

### Actual results

Crashed immediately after starting

### On which platforms did you notice this:

 - OS: Windows 10
 - Using docker for windows and the 3grander/dagda image
 - Docker version 18.06.1-ce, build e68fc7a

### Backtrace

```
<2018-11-09 08:24:45,218> <ERROR> <DagdaServer> <docker_driver> <__init__:39> <Error while fetching Docker server API version: Assuming Travis CI tests.>
<2018-11-09 08:24:45,556> <WARNING> <DagdaServer> <sysdig_falco_monitor> <pre_check:83> <I'm running inside a docker container, so I can't check if the kernel headers are installed in the host operating system. Please, review it!!>
<2018-11-09 08:24:45,557> <ERROR> <DagdaServer> <dagda_server> <run:103> <Error while fetching Docker server API version.>
<2018-11-09 08:24:45,558> <WARNING> <DagdaServer> <dagda_server> <run:104> <Runtime behaviour monitor disabled.>
 * Serving Flask app "api.dagda_server" (lazy loading)
 * Environment: production
<2018-11-09 08:24:45,561> <ERROR> <DagdaServer> <dagda> <main:46> <'NoneType' object has no attribute 'events'>
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/opt/app/cli/dagda_cli.py", line 43, in execute_dagda_cmd
    ds.run()
  File "/opt/app/api/dagda_server.py", line 92, in run
    docker_daemon_events_monitor.run()
  File "/opt/app/analysis/runtime/docker_events_monitor.py", line 45, in run
    for event in self.docker_driver.docker_events():
  File "/opt/app/driver/docker_driver.py", line 114, in docker_events
    return self.cli.events()
AttributeError: 'NoneType' object has no attribute 'events'
```

### Solution

I don't know what I am doing wrong !

**Comment by Docteur-RS** [comment]
To connect to my own mongoDB I updated the docker-compose from :

```yaml
version: '2'
services:
  dagda:
    build: .
    image: 3grander/dagda:0.8.0
    container_name: dagda
    networks:
      - mdb
    entrypoint: python dagda.py start -s 0.0.0.0 -p 5000 -m 192.168.99.100 -mp 27017
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    depends_on:
      - vulndb
  vulndb:
    image: mongo
    container_name: vulndb
    networks:
      - mdb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
networks:
  mdb:
    external: false
```

to
```yaml
version: '2'
services:
  dagda:
    build: .
    image: 3grander/dagda:0.8.0
    container_name: dagda
    networks:
      - mdb
    entrypoint: python dagda.py start -s 0.0.0.0 -p 5000 -m 192.168.99.100 -mp 27017
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
networks:
  mdb:
    external: false
```
Now that the docker socket is mountedI don't have anymore errors :-)

BUT to interact with the container I must do the exports myself in the following manner :
` docker exec -it 3e49abbfd862  /bin/sh -c "export DAGDA_HOST='192.168.99.100' && export DAGDA_PORT=5000 && python3 dagda.py docker images"`

**Am I using it wrong ?** It feels weird to have to do the exports in the command line itself.

**Comment by eliasgranderubio** [comment]
If you use docker-compose for running  *Dagda*, the best option would be to use the [REST API](https://github.com/eliasgranderubio/dagda/wiki/REST-API) from your host.

Anyway, if you prefer running *Dagda* CLI within docker container, try to avoid "-c", I mean, run:
```
~$ docker exec -it 3e49abbfd862 /bin/sh 
```
When you are in this point, only must export the variables once and you could run all *Dagda* commands without export these variables again.

**Comment by Docteur-RS** [comment]
I get what you mean.
Unfortunatly logging into the container is not the simplest thing to accomplish when scripting the scans, getting history etc...

I find it a bit disappointing that the CLI is kind of unreachable easily when using docker-compose :-)

Thanks for your help, I guess I'll use the REST API then.

**Comment by moisesdelacruz301997** [comment]
Hi, when I run the dagda Image in docker-compose, it automatically exists. What should be the problem?

I cloned the project, build it as docker Image, then when I try to run it as docker-comose this happens,

![Screen Shot 2019-12-02 at 3 08 08 PM](https://user-images.githubusercontent.com/58415523/69937270-3bccde80-1515-11ea-9241-bcf92d3f98a4.png)

**Comment by Docteur-RS** [comment]
@moisesdelacruz301997 Hi. Can you show your Dockerfile ?

**Comment by moisesdelacruz301997** [comment]
Hi @Docteur-RS,

Sorry I forgot to attach this.

![Screen Shot 2019-12-02 at 4 56 45 PM](https://user-images.githubusercontent.com/58415523/69945587-d4b72600-1524-11ea-821d-1f154ee20c4e.png)

**Comment by Docteur-RS** [comment]
@moisesdelacruz301997 My bad, I meant the docker-compose file.

**Comment by moisesdelacruz301997** [comment]
**docker-compose.yml**

![Screen Shot 2019-12-02 at 5 08 00 PM](https://user-images.githubusercontent.com/58415523/69946305-59567400-1526-11ea-85a1-87e1edf9eb65.png)

**Comment by moisesdelacruz301997** [comment]
Hi, the issue above is not happening anymore, I resolved the issue by re-cloning the project.

But now I'm having a new issue whenever I start the server. 

This is the error that is displaying.


![Screen Shot 2019-12-02 at 5 14 21 PM](https://user-images.githubusercontent.com/58415523/69946756-3c6e7080-1527-11ea-9c77-5d8ea0c47418.png)

**Comment by Docteur-RS** [comment]
Strange... Does `docker logs <container>` prints anything usefull ?

* Maybe try to shift your container type if you are on windows from [windows containers] to [linux containers] or the other way arround.
* Maybe cut the docker-compose in half. Launch **Vulndb** on its own and then update the `-m` option of the entry point line to the address IP of vulndb (instead of writting "vulndb" directly). To get the IP of vulndb you can use `docker inspect`.

**Comment by moisesdelacruz301997** [comment]
Hi @Docteur-RS ,
Re-cloning the project fixed my issue here.
Thanks a lot for your effort to investigate my issue.

**Comment by Docteur-RS** [comment]
@moisesdelacruz301997 Haha no problem.  
If all problems on earth could be solved by re-cloning that would be wonderfull !
