### ISSUE TITLE
Dagda won't start, complaining about Docker Module not found

### ISSUE THREAD

**Issue by darthmolen** [eliasgranderubio/dagda#45]
### Short description

I was trying to install dagda on Ubuntu 18.04

### Reproduction steps
Install all pre-reqs including docker and mongo
git clone the repo
try and start dagda with the following command:

```sudo python3 dagda.py start```
### Expected results

I expected the dagda service to start

### Actual results

Instead of the service starting, it gave me that there is no "docker" module. Docker is installed. I can run a ```docker pull hello-world
docker run hello-world```

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu
 - OS Version: 18.04 
- Python version: 3.7
 - Docker version: Docker version 18.09.1, build 4c52b90
 - MongoDB version 4.0.5

### Backtrace

```
 <ERROR> <DagdaServer> <dagda> <main:46> <No module named 'docker'>
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/usr/lib/dagda/dagda/cli/dagda_cli.py", line 32, in execute_dagda_cmd
    from api.dagda_server import DagdaServer
  File "/usr/lib/dagda/dagda/api/dagda_server.py", line 27, in <module>
    from api.internal.internal_server import InternalServer
  File "/usr/lib/dagda/dagda/api/internal/internal_server.py", line 22, in <module>
    from driver.docker_driver import DockerDriver
  File "/usr/lib/dagda/dagda/driver/docker_driver.py", line 20, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
```

**Comment by eliasgranderubio** [comment]
Probably you ran python pip without sudo and therefore docker module is not found. Could you try to run dagda without sudo?

**Comment by darthmolen** [comment]
I tried this without sudo... i also did the same command after doing sudo -s (basically as root). All gave the same error.

I've already added a docker group and gave my account rights to do docker without sudo.

How do I check what you said "Probably you ran python pip without sudo". pretty much everything on this system for installation purposes had to be done under sudo.

**Comment by darthmolen** [comment]
pip3 is in /usr/bin

**Comment by eliasgranderubio** [comment]
You are right! Docker, Python and Pip3 must be installed with root user. On the other hand and optionally, mongodb could be a docker container and you wouldn't need install it with a root user.

Anyway, when you install the python dependencies listed in the `requirements.txt` file with pip3 tool, sometimes the dependencies are installed in a virtual env created by python to your non root user and others, python installs the dependencies for all users in your operative system. Could you verify for what user are available the python dependencies installed?

**Comment by darthmolen** [comment]
so, interestingly enough. I had installed docker manually and deleted it from the requirements document. 

so on a lark and based on your suggestion, i dropped down into root with sudo -s and ran the requirements.txt that came from the source. It actually installed an older version of docker and dockerpy, and now it works....

So yeah, in your FAQ section, you might want to recommend that people install the requirements.txt document from root and to not do the components manually.
