### ISSUE TITLE
choice of port 5000 conflicts with standard docker registry port

### ISSUE THREAD

**Issue by xmrk** [eliasgranderubio/dagda#47]
### Short description

Quickly starting up dagda using the docker-compose.yml file fails on a host that is also running a persistent docker registry container (https://hub.docker.com/_/registry).  This is a common approach as described in the Docker documentation: https://docs.docker.com/registry/deploying/.  The dagda port should perhaps be changed to something else.

### Reproduction steps

Per instructions, run docker-compose build && docker-compose up

### Expected results

A dagda system starts up without intervention.

### Actual results

ERROR: for dagda  Cannot start service dagda: b'driver failed programming external connectivity on endpoint dagda (a79806fca4ca37a8b41b12ff9cdbfc82563691c8370b2e048750c347b78401a5): Bind for 0.0.0.0:5000 failed: port is already allocated'

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu
 - OS Version: Linux myhost 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Python version: from image 3grander/dagda:0.8.0
 - Docker version: Docker version 18.09.2, build 6247962
 - MongoDB version: from image mongo:latest

### Backtrace

...

### Solution

Changed all port 5000 references in docker-compose to a different port.

**Comment by eliasgranderubio** [comment]
Hi @xmrk,

The port sets in the docker-compose for dagda server is the default port for the different python frameworks as flask, WSGI, etc.

Feel free for changing it if you need, but the source code in this repo will not be changed.

Regards.
