### ISSUE TITLE
Sort Memory errors in Mongodb

### ISSUE THREAD

**Issue by ilcapone** [eliasgranderubio/dagda#56]
Hi again :)

### Short description

Trying to extract the reports of statistical analysis, I got this error `Sort operation used more than the maximum 33554432 bytes of RAM`

I could solve it by opening a shell in the mongdb container and modifying the `internalQueryExecMaxBlockingSortBytes` parameter to 134 MB with this command:

`db.adminCommand({'setParameter':1, 'internalQueryExecMaxBlockingSortBytes':134217728})`

A more in-depth description of the space restriction and how to solve it can be found here:
`https://mobilemonitoringsolutions.com/memory-errors-mongodb-resolve/`

### Persistent error

When for other reasons I had to restart the mongo database I lost the configuration and I had this error again because I did not commit to this image.

It would be possible to increase the size of mongo by default, or that somehow through the api of the dagda server configure this parameter?

### Backtrace

Dagda server log error
```
dagda     | 2019-04-03T06:21:45.584498635Z pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
```

Thanks in advance !!

**Comment by eliasgranderubio** [comment]
Hi @ilcapone ,

Before fix the issue by a mongodb admin command, could you describe me what query or analysis you were doing? Perhaps, it's necessary pagination in some API or the queries should be done in others way.

Regards.

**Comment by eliasgranderubio** [comment]
Closed due to inactivity.
