### ISSUE TITLE
How to scan a local image using dagda.

### ISSUE THREAD

**Issue by nehaj27** [eliasgranderubio/dagda#60]
### Short description

I was trying to do get an analysis of local image.

### Reproduction steps
1. I downloaded the vulnerabilities by 'python3 dagda.py vuln --init'
and it showed the status updated after a while.
2. 'python3 dagda.py check --docker_image nmap-dist:latest'
3. 'python3 dagda.py history nmap-dist:latest --id 5ce791385ea27b39940ecfeb'

### Expected results

I expected that by analyzing the docker image 'nmap-dist' and showing the report by using the command 'python3 dagda.py history nmap-dist:latest --id 5ce791385ea27b39940ecfeb' it would give a detailed analysis.

### Actual results

```
{
    "err": 404,
    "msg": "History not found"
}
```

### On which platforms did you notice this:

Please complete the following information:

ubuntu:18.04
OS Version: Linux esypc5 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Python version: [Python 3.6.7]
Docker version 18.09.6, build 481bc77
MongoDB version
db version v3.6.3
git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
OpenSSL version: OpenSSL 1.1.0g 2 Nov 2017
allocator: tcmalloc
modules: none
build environment:
distarch: x86_64
target_arch: x86_64

### Backtrace

```
Please copy paste the backtrace here if available
```

### Solution

Kindly help me with the same.

**Comment by eliasgranderubio** [comment]
Please, review the next comment of your other [issue](https://github.com/eliasgranderubio/dagda/issues/59#issuecomment-496025816).

Regards.
