### ISSUE TITLE
Bug in _untar_layers() function

### ISSUE THREAD

**Issue by adf2007** [eliasgranderubio/dagda#62]
### Short description
I think there is a bug in dagda/analysis/static/util/util.py :

def _untar_layers(dir, layers):
    output = {}
    # Untar layer filesystem bundle
    for layer in layers:
        tarfile = TarFile(dir + "/" + layer)
        for member in tarfile.getmembers():
            output[member.name] = member
    for member_name in output:
        try:
            tarfile.extract(output[member_name], path=dir, set_attrs=False)
        except (ValueError, ReadError) as ex:
            if InternalServer.is_debug_logging_enabled():
                message = "Unexpected exception of type {0} occurred while untaring the docker image: {1!r}" \
                    .format(type(ex).__name__, ex.get_message() if type(ex).__name__ == 'DagdaError' else ex.args)
                DagdaLogger.get_logger().debug(message)
        except PermissionError as ex:
            message = "Unexpected error occurred while untaring the docker image: " + \
                      "Operation not permitted on {0!r}".format(member_name)
            DagdaLogger.get_logger().warn(message)

    # Clean up
    for layer in layers:
        clean_up(dir + "/" + layer[:-10])

### Solution - It should be like this:

def _untar_layers(dir, layers):
    
    # Untar layer filesystem bundle
    for layer in layers:
        tarfile = TarFile(dir + "/" + layer)
        output = {}
        for member in tarfile.getmembers():
            output[member.name] = member
        for member_name in output:
            try:
                tarfile.extract(output[member_name], path=dir, set_attrs=False)
            except (ValueError, ReadError) as ex:
                if InternalServer.is_debug_logging_enabled():
                    message = "Unexpected exception of type {0} occurred while untaring the docker image: {1!r}" \
                        .format(type(ex).__name__, ex.get_message() if type(ex).__name__ == 'DagdaError' else ex.args)
                    DagdaLogger.get_logger().debug(message)
            except PermissionError as ex:
                message = "Unexpected error occurred while untaring the docker image: " + \
                        "Operation not permitted on {0!r}".format(member_name)
                DagdaLogger.get_logger().warn(message)

    # Clean up
    for layer in layers:
        clean_up(dir + "/" + layer[:-10])

**Comment by eliasgranderubio** [comment]
Sorry @adf2007 but I don't understand why you think here is a bug there. I have tested that exception flow and looks like it works fine.

Have you any case where you get ValueError or other similar exception if `__name__` is used?

**Comment by eliasgranderubio** [comment]
Closed due to inactivity.

**Comment by adf2007** [comment]
> Sorry @adf2007 but I don't understand why you think here is a bug there. I have tested that exception flow and looks like it works fine.
> 
> Have you any case where you get ValueError or other similar exception if `__name__` is used?

The key point of the bug is the tarfile variable.When you run "tarfile.extract(output[member_name], path=dir, set_attrs=False)"，the tarfile is just the last time value of the "tarfile = TarFile(dir + "/" + layer)", the value of trafile is not right. You should update tarfile everytime when you run "tarfile.extract(output[member_name], path=dir, set_attrs=False)".

**Comment by eliasgranderubio** [comment]
Reviewed the bug. Thank you @adf2007 .
