### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'events'

### ISSUE THREAD

**Issue by ranvijay-sachan** [eliasgranderubio/dagda#63]
Hi I am not using docker, getting below error. Can you please take a look.

(dagda) ubuntu@ubuntu-Latitude-E6420:~/dagda/dagda$ python3 dagda.py start
<2019-07-06 10:46:02,709> <ERROR> <DagdaServer> <docker_driver> <__init__:39> <Error while fetching Docker server API version: Assuming Travis CI tests.>
<2019-07-06 10:46:02,778> <ERROR> <DagdaServer> <dagda> <main:46> <'NoneType' object has no attribute 'events'>
Traceback (most recent call last):
  File "dagda.py", line 35, in main
    r = execute_dagda_cmd(cmd=cmd, args=parsed_args)
  File "/home/ubuntu/dagda/dagda/cli/dagda_cli.py", line 43, in execute_dagda_cmd
    ds.run()
  File "/home/ubuntu/dagda/dagda/api/dagda_server.py", line 93, in run
    docker_daemon_events_monitor.run()
  File "/home/ubuntu/dagda/dagda/analysis/runtime/docker_events_monitor.py", line 45, in run
    for event in self.docker_driver.docker_events():
  File "/home/ubuntu/dagda/dagda/driver/docker_driver.py", line 114, in docker_events
    return self.cli.events()
AttributeError: 'NoneType' object has no attribute 'events'
Serving on http://localhost:5000
<2019-07-06 10:46:02,836> <ERROR> <DagdaServer> <dagda_server> <run:104> <Error while fetching Docker server API version.>
<2019-07-06 10:46:02,837> <WARNING> <DagdaServer> <dagda_server> <run:105> <Runtime behaviour monitor disabled.>

**Comment by eliasgranderubio** [comment]
Hi @ranvijay-sachan ,

Sometimes this error occurs when docker version and the pyhon library for docker don't match. 

I suppose you have the last version of **Dagda** and its dependencies but, what are your os and docker version?

**Comment by ranvijay-sachan** [comment]
Hi @eliasgranderubio thanks for the reply.

I am using `dagda.py 0.8.0` , `Docker version 18.09.7, build 2d0083d` and os `ubuntu 16.04`.
Do i need to change anything?
