### ISSUE TITLE
Max retries exceeded with url: /v1/check/containers/cf04e94c4510  || Failed to establish a new connection: [Errno 111] Connection refused]

### ISSUE THREAD

**Issue by Ajitesh2012** [eliasgranderubio/dagda#65]
Hello Team,

After cloning the repo, i ran below command to scan below images 
![image](https://user-images.githubusercontent.com/47196587/63106574-065ab000-bf7b-11e9-84da-10c0a59b3639.png). Please suggest where things going wrong

OS: Ubuntu 18.04
python : verision 3.7 and 2.7 both installed and uptodate

On scanning i am getting TPConnection object at 0x7fca3b422ef0>: Failed to establish a new connection: [Errno 111] Connection refused')) PFB screenshot
![image](https://user-images.githubusercontent.com/47196587/63106507-df03e300-bf7a-11e9-860e-465a9ded4e1a.png)

Kind regards
Ajitesh

**Comment by eliasgranderubio** [comment]
Hi @Ajitesh2012 ,

Have you run the [start sub-command](https://github.com/eliasgranderubio/dagda/wiki/CLI-Usage#start-sub-command) before try to check any docker image?

Regards.

**Comment by Ajitesh2012** [comment]
Hi Elias,

Thankou for the reply i figure it out i had ran about command earlier was well. issue was with pip version by default i have been installing pip in version 2.7 but application works with pip3 so i install pip3 for pyhton 3.7 and it worked.

root@pc101:~/dagda/dagda# python3 dagda.py docker images
[
    {
        "created": "2019-07-16 13:57:04",
        "id": "1160e60f64f1",
        "size": "385.3MB",
        "tags": [
            "bkimminich/juice-shop:latest"
        ]
    },
    {
        "created": "2019-07-10 22:20:30",
        "id": "7bb157f0dd75",
        "size": "826.5MB",
        "tags": [
            "sonarqube:latest"
        ]
    },
    {
        "created": "2018-10-12 17:49:01",
        "id": "ab0d83586b6e",
        "size": "678.8MB",
        "tags": [
            "vulnerables/web-dvwa:latest"

Kinds Regards
Ajitesh Baloria
