### ISSUE TITLE
Using Dagda behind a proxy server

### ISSUE THREAD

**Issue by televi** [eliasgranderubio/dagda#67]
### Short description

Trying to do python dagda.py vuln --init on a running daga (started via docker-compose up) behind a corporate proxy server/firewall.

### Reproduction steps

1. git clone daga from source
1. install prereq's (including mongo)
1.  dagda via docker-compose build --bulid-arg http_proxy=${http_proxhy} --build-arg https_proxy=${https_proxy} 
1. start dagda via docker-compose up -d
1.  run python dadga.py vuln --init

### Expected results

python dagda.py vuln --init_status shows some form of complete

### Actual results

python dagda.py vuln --init_status showed an exception about connection timeouts

### On which platforms did you notice this:

 - OS: CentOS
 - OS Version: 7.5 (3.10.0-957.12.2.el7.x86_64)
 - Python version: 3.7
 - Docker version: 19.03.02
 - MongoDB version: latest

### Backtrace

N/A

### Solution

When building via docker-compose, the dadga container failed unless I passed it the http_proxy and https_proxy vars to docker-compose build.  That didn't persist however - those vars are not set inside the dagda container.  For fix that, I simply added the following to the Dockerfile:
```
ENV http_proxy=${http_proxy}
ENV https_proxy=${https_proxy}
```
I rebuilt again using the above docker-compose build and docker-compose up commands and ran vuln --init again and now the service is happily download all the things.

**Comment by eliasgranderubio** [comment]
Hi @televi ,
The docker image should not be modified, so if you need the env variables behind your corporate proxy/firewall, you should be set them in the docker compose file but not in the dokerfile. Please, read the next [doc](https://docs.docker.com/compose/environment-variables/) for more details.
