### ISSUE TITLE
vuln init status using REST API displaying an Error

### ISSUE THREAD

**Issue by moisesdelacruz301997** [eliasgranderubio/dagda#69]
### When I run vuln/init I'm having this result,

{
  "msg": "Accepted the init db request"
}

but when I get the vuln init-status, i'm having this result,

{
  "status": "Unexpected exception of type TypeError occurred: ('documents must be a non-empty list',)",
  "timestamp": "2019-12-10 14:06:23.798047"
}

this is also displayed in logs (im running dagda in docker-compose)

dagda     | <2019-12-10 14:06:23,797> <ERROR> <DagdaServer> <dagda_server> <_init_or_update_db:155> <Unexpected exception of type TypeError occurred: ('documents must be a non-empty list',)>
Exception in thread Thread-25:
dagda     | Traceback (most recent call last):
dagda     |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
dagda     |     self.run()
dagda     |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
dagda     |     self._target(*self._args, **self._kwargs)
dagda     |   File "/opt/app/vulnDB/db_composer.py", line 152, in _threaded_cve_gathering
dagda     |     cve_list = get_cve_list_from_file(compressed_content, i)
dagda     |   File "/opt/app/vulnDB/ext_source_util.py", line 62, in get_cve_list_from_file
dagda     |     xml_file_content = zlib.decompress(compressed_content, 16 + zlib.MAX_WBITS)
dagda     | zlib.error: Error -3 while decompressing data: incorrect header check
dagda     | 
dagda     | <2019-12-10 14:06:23,797> <ERROR> <DagdaServer> <dagda_server> <_init_or_update_db:155> <Unexpected exception of type TypeError occurred: ('documents must be a non-empty list',)>

**Steps,**

1. Start Dagda server in docker-compose
2. After running it, run vuln init

**Other things that can be helpful,**

docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Comment by eliasgranderubio** [comment]
Duplicated by issue #68
