### ISSUE TITLE
LICENSE not found

### ISSUE THREAD

**Issue by rsrdesarrollo** [eliasgranderubio/dagda#7]
This project has no LICENSE file.
In Spanish legislation this means that the project is under strict Copyright, making nobody able to contribute. Also, it may avoid contributions from other organisations in the world. 

Please, consider adding to your project the LICENSE file you like the most.

More info: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by eliasgranderubio** [comment]
I agree with you @rsrdesarrollo but I forgot add the LICENSE file.

I'm going to update the repo right now with the Apache 2.0 License, don't worry!
