### ISSUE TITLE
"Exception in thread Thread-2" when using agent subcommand

### ISSUE THREAD

**Issue by JakobKern** [eliasgranderubio/dagda#73]
### Short description

I was trying to do start an agent on a docker image
in the same way it does in the readme.

### Reproduction steps

1. Start Dagda server with the help of docker-compose up
2. Type the Dagda CLI command 
    `python3 dagda.py agent localhost:5000 -i imiell/bad-dockerfile`

### Expected results

`{`
  `  "id": "5e14d53116b40a0001149cc9",`
   ` "image_name": "imiell/bad-dockerfile"`
`}`

### Actual results

`Exception in thread  Thread-2:`
`Traceback (most recent call last):`
 ` File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner`
   ` self.run()`
`  File "/usr/lib/python3.5/threading.py", line 862, in run`
  `  self._target(*self._args, **self._kwargs)`
 ` File "/home/jakob/dagda/dagda/analysis/analyzer.py", line 243, in _threaded_dependencies`
  `  temp_dir=temp_dir))`
 ` File "/home/jakob/dagda/dagda/analysis/static/dependencies/dep_info_extractor.py", line 51, in` `get_dependencies_from_docker_image`
   ` dependencies_info = json.loads(read_4depcheck_output_file(filtered_image_name))`
 ` File "/home/jakob/dagda/dagda/analysis/static/dependencies/dep_info_extractor.py", line 77, in` `read_4depcheck_output_file`
 `   raise DagdaError('4depcheck output file [' + filename + '] not found.')`
`exception.dagda_error.DagdaError`

`{`
 `   "id": "5e14d53116b40a0001149cc9",`
   ` "image_name": "imiell/bad-dockerfile"`
` }`

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu
 - OS Version: 16.04.1
 - Python version: Python 2.7.12
 - Docker version: Docker version 19.03.5, build 633a0ea838
 - MongoDB version: db version v2.6.10

### Additional info:

No errors occur when using the vuln/check/history command

**Comment by eliasgranderubio** [comment]
The error was in the 4depcheck project because the json of RetireJS had changed.

Please @JakobKern , test again and update me if the issue is fixed.

**Comment by eliasgranderubio** [comment]
Closed due to inactivity

**Comment by liangxiaoxiaoxiao** [comment]
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dagda-master/dagda/analysis/analyzer.py", line 243, in _threaded_dependencies
    temp_dir=temp_dir))
  File "/root/dagda-master/dagda/analysis/static/dependencies/dep_info_extractor.py", line 51, in get_dependencies_from_docker_image
    dependencies_info = json.loads(read_4depcheck_output_file(filtered_image_name))
  File "/root/dagda-master/dagda/analysis/static/dependencies/dep_info_extractor.py", line 77, in read_4depcheck_output_file
    raise DagdaError('4depcheck output file [' + filename + '] not found.')
exception.dagda_error.DagdaError

I got the same error
