### ISSUE TITLE
Is it possible to run dagda as a container?

### ISSUE THREAD

**Issue by sarathm32** [eliasgranderubio/dagda#76]
### Short description

I was trying to run dagda as a container rather than directly run it on the host.

I was able to successfully run dagda directly on the host following the steps mentioned. But is it possible to run it in a container so that I don't have to install all the python requirements on the host.

There is a dagda container 3grander/dagda. Is it possible to start dagda inside this container and connect to the db in the mongo contaner. 

Just want to know if this is possible.

### On which platforms did you notice this:

Please complete the following information:

 - OS: Ubuntu 16.04
 - OS Version: Linux ubu16-s 4.4.0-142-generic 
 - Python version: 3.5.2
 - Docker version 18.09.7
 - MongoDB version 2.6.10

**Comment by eliasgranderubio** [comment]
Hi @sarathm32 ,

You have an example in the [docker-compose.yml](https://github.com/eliasgranderubio/dagda/blob/master/docker-compose.yml). If you already have a MongoDB, you only need run the dagda docker container modifying the entrypoint with the correct MongoDB endpoint.

Regards.
