### ISSUE TITLE
Falcosecurity/ falco output file not found.

### ISSUE THREAD

**Issue by sahan80** [eliasgranderubio/dagda#93]
### Short description

After starting the dagda server, getting as error as 
<ERROR> <DagdaServer> <dagda_server> <run:104> <Falcosecurity/falco output file not found.>

### Reproduction steps

1. Start Dagda server with the parameters  (sudo python3.7 dagda.py start)
2. Wait for few seconds then it will throw an error as falco output file not found

### On which platforms did you notice this:

Please complete the following information:

 - OS: [Ubuntu 20.0.4
 - OS Version: [e.g. (~$ uname -a)]
 - Python version:  Python 3.7
 - Docker version 19.03.11

### Backtrace

ubuntu@ubuntu2004:~/dagda/dagda$ sudo python3.7 dagda.py start
Serving on http://localhost:5000
<2020-12-23 06:30:06,464> <ERROR> <DagdaServer> <dagda_server> <run:104> <Falcosecurity/falco output file not found.>
<2020-12-23 06:30:06,464> <WARNING> <DagdaServer> <dagda_server> <run:105> <Runtime behaviour monitor disabled.>

**Comment by jakobkuehl** [comment]
I had the same issue, this fixed it for me:

Clear your local /tmp. Dagda creates files there that can cause trouble if you restart dagda
remove the folco docker containers and images so dagda has to download them again
and if you don't have it you should install sysdig [https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux](url)

**Comment by eliasgranderubio** [comment]
This issue should be fixed with my last commit.

**Comment by Parvin555** [comment]
This issue is still there!

**Comment by mushroom1998** [comment]
This issue is still there!

**Comment by 1karu32s** [comment]
this issue is ssssstill there!!!!!!!!!!!!!
